{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "044456d9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "\n",
    "# ✅ CSV 로드\n",
    "df = pd.read_csv(\"../data/Mcdelivery_menu_prices_Kacl.csv\")\n",
    "df.columns = df.columns.str.strip()\n",
    "df['칼로리(Kcal)'] = pd.to_numeric(df['칼로리(Kcal)'], errors='coerce')\n",
    "\n",
    "st.title(\"🍔 햄버거 추천 웹사이트\")\n",
    "st.markdown(\"### 당신에게 딱 맞는 맥도날드 버거를 추천해드릴게요!\")\n",
    "\n",
    "# ✅ 사용자 입력\n",
    "col1, col2, col3 = st.columns(3)\n",
    "with col1:\n",
    "    gender = st.radio(\"성별\", (\"남\", \"여\"))\n",
    "with col2:\n",
    "    height = st.number_input(\"신장 (cm)\", min_value=100, max_value=250, value=170)\n",
    "with col3:\n",
    "    weight = st.number_input(\"체중 (kg)\", min_value=30, max_value=200, value=65)\n",
    "\n",
    "set_choice = st.radio(\"🍟 버거를 어떤 방식으로 추천받고 싶나요?\", (\"단품\", \"세트\"))\n",
    "\n",
    "# ✅ 일일 권장 섭취량 계산\n",
    "if gender == \"남\":\n",
    "    bmr = 10 * weight + 6.25 * height - 5 * 25 + 5\n",
    "else:\n",
    "    bmr = 10 * weight + 6.25 * height - 5 * 25 - 161\n",
    "\n",
    "total_kcal = round(bmr * 1.2)\n",
    "st.success(f\"📊 일일 권장 섭취량은 약 **{total_kcal} kcal** 입니다.\")\n",
    "\n",
    "# ✅ 버거 필터링\n",
    "burger_df = df[df['카테고리'].str.contains(\"버거\")].copy()\n",
    "\n",
    "# ✅ 단품 추천\n",
    "if set_choice == \"단품\":\n",
    "    burger_df['칼로리당_가격'] = burger_df['가격'] / burger_df['칼로리(Kcal)']\n",
    "    burger_df_sorted = burger_df.sort_values('칼로리당_가격')\n",
    "    best = burger_df_sorted.iloc[0]\n",
    "\n",
    "    st.subheader(\"🍔 단품 기준 가성비 최고의 버거 추천\")\n",
    "    st.markdown(f\"\"\"\n",
    "    - **메뉴:** {best['메뉴']}\n",
    "    - **가격:** {best['가격']}원\n",
    "    - **칼로리:** {best['칼로리(Kcal)']} kcal\n",
    "    - **칼로리당 가격:** {best['칼로리당_가격']:.2f} 원/kcal\n",
    "    \"\"\")\n",
    "\n",
    "# ✅ 세트 추천\n",
    "else:\n",
    "    fries = df[df['메뉴'].str.contains('후렌치 후라이', na=False)].iloc[0]\n",
    "    drink = df[df['카테고리'].str.contains('음료')].iloc[0]\n",
    "\n",
    "    burger_df['총칼로리'] = burger_df['칼로리(Kcal)'] + fries['칼로리(Kcal)'] + drink['칼로리(Kcal)']\n",
    "    burger_df['칼로리당_가격'] = burger_df['가격'] / burger_df['총칼로리']\n",
    "    burger_df_sorted = burger_df.sort_values('칼로리당_가격')\n",
    "    best = burger_df_sorted.iloc[0]\n",
    "\n",
    "    st.subheader(\"🍟 세트 기준 가성비 최고의 버거 추천\")\n",
    "    st.markdown(f\"\"\"\n",
    "    - **메뉴:** {best['메뉴']} + {fries['메뉴']} + {drink['메뉴']}\n",
    "    - **총 칼로리:** {best['총칼로리']} kcal\n",
    "    - **가격:** {best['가격']}원\n",
    "    - **칼로리당 가격:** {best['칼로리당_가격']:.2f} 원/kcal\n",
    "    \"\"\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
